# Generated by Django 6.1.1 on 2026-10-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocoded',
            field=models.BooleanField(default=False),
        ),
    ]
