# Generated by Django 6.1.1 on 2026-10-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_fuelstation_geocoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='location_key',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
