# Generated by Django 6.1.1 on 2026-10-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_fuelstation_location_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('city', 'state'), name='unique_city_state')],
            },
        ),
    ]
